### PR TITLE
Support configuring predicates via command-line flag

### PR DESCRIPTION
**Pull request by TaoYang526**
This is initial PR for #62 .
@yangwwei @wilfred-s , please help to review. Thanks.

### CODE REVIEW

**Comment by yangwwei** [comment]
Hi @TaoYang526 

This is what we wanted. Just one thing we need to make predicates options available from CLI. Usually, we can do

`make build`

this builds the binary under `./_output/bin/k8s_yunikorn_scheduler`, then we can run `./_output/bin/k8s_yunikorn_scheduler -h`, this returns us the available options:

```
Usage of ./_output/bin/k8s_yunikorn_scheduler:
  -clusterId string
    	cluster id (default "my-kube-cluster")
  -clusterVersion string
    	cluster version (default "0.1")
  -dispatchTimeout duration
    	timeout in seconds when dispatching an event (default 5m0s)
  -eventChannelCapacity int
    	event channel capacity of dispatcher (default 1048576)
  -interval duration
    	scheduling interval in seconds (default 1s)
  -kubeBurst int
    	the maximum burst for throttle to kubernetes master from this client (default 1000)
  -kubeConfig string
    	absolute path to the kubeconfig file
  -kubeQPS int
    	the maximum QPS to kubernetes master from this client (default 1000)
  -logEncoding string
    	log encoding, json or console. (default "console")
  -logFile string
    	absolute log file path
  -logLevel int
    	logging level, available range [-1, 5], from DEBUG to FATAL.
  -name string
    	name of the scheduler (default "yunikorn")
  -policyGroup string
    	policy group (default "queues")
  -volumeBindTimeout duration
    	timeout in seconds when binding a volume (default 10s)
```

We need to add predicates options in the help content. So people know what to add if they want.

**Comment by yangwwei** [comment]
And looks like we will need to put all values from https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go here.

**Comment by TaoYang526** [comment]
Thanks @yangwwei for the review.
How about to update the predicates flag and fatal log as follows?
```
predicates := flag.String("predicates", "", "comma-separated list of predicates, "+
		"which will be validated as per the definition of predicatesOrdering in "+
		"https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go, "+
		"the scheduler will exit if any invalid predicates exist.")

msg := "please refer to the definition of predicatesOrdering in https://" +
					"github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go " +
					"for valid predicates."
return nil, fmt.Errorf("configured predicate is invalid: %s, message: %s", parsedPredicate, msg)

```
If the value of predicates option contains invalid predicate, the pod of yunikorn-scheduler will be in the Error state and users can see the fatal logs via executing 'kubectl logs <YK-POD-ID> yunikorn-scheduler-k8s'.

**Comment by TaoYang526** [comment]
Thanks @yangwwei for the suggestion about directly showing all valid predicates, updated now.

**Comment by yangwwei** [comment]
LGTM, thanks @TaoYang526

**Pull request merged**
